### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by ecxia** [chicagopython/buddy_mentorship#119]
When we add new features, we need some way to let users know about them.

**Comment by cjoshmartin** [comment]
I use this for my personal projects. It will create a release for you with the release notes based on the commits: ub.com/semantic-release/semantic-release

**Comment by rifferreinert** [comment]
Hi @cjoshmartin this looks pretty cool. it looks like it also automatically creates a release tag based on the commit message? We plan on versioning at the end of each (two week) sprint. Can it be used manually to pull a bunch of commits into the next release?
