### ISSUE TITLE
Support End States for Requests

### ISSUE THREAD

**Issue by raymondberg** [chicagopython/buddy_mentorship#124]
## Problem

If a mentorship continues for 3 months and ends naturally (or otherwise), the state of the pairing is no longer 
the same as when it was `Requested`, nor when it was `Accepted`. It is in a new state of `Completed` or 
similar language. 

## Proposal

Allow for a Mentor or Mentee to change the state of an `Accepted` request to `Completed`. In doing so, 
`Completed` requests no longer count to capacity outlined in #122, and the mentor will show up in #123 
if they are now under their ideal capacity.

**Comment by ZaxR** [comment]
This ticket will focus on just adding a new state for completed. The automatic management vs capacity will be added in #128
