### ISSUE TITLE
Send e-mail notifications on match

### ISSUE THREAD

**Issue by ZaxR** [chicagopython/buddy_mentorship#13]
Depends on #12

**Comment by eevelweezel** [comment]
Added these to settings and tested the configuration against SendGrid.  The integration is working, but this is somewhat blocked, since the matching functionality doesn't seem to be built yet.  Is someone working on this?  I'd be happy to start on that, but I don't see a ticket for it.

**Comment by rifferreinert** [comment]
We also need a final email when the mentor accepts which will give both parties contact information for the other
