### ISSUE TITLE
Deploy core app

### ISSUE THREAD

**Issue by ZaxR** [chicagopython/buddy_mentorship#15]

**Comment by ZaxR** [comment]
Originally intended to be stood up on Heroku. Dev version is already on Heroku, but prod deployment may live on Digital Ocean if they sponsor us.

**Comment by ecxia** [comment]
We've deployed prod version in Heroku at https://chipymentor.org. Right now site is in maintenance mode while we finish building out MVP features & get some polish in.

**Comment by ecxia** [comment]
deploooooooooyyyyyyyyeeeeeedd!
