### ISSUE TITLE
Create MVP Data Model

### ISSUE THREAD

**Issue by ZaxR** [chicagopython/buddy_mentorship#7]
Django Model implementations should look to the data model for the appropriate fields/types/linkages.

**Comment by ZaxR** [comment]
Previously commented this on the wrong issue by mistake:

Ignore the casing for the table/field names - can be w/e the Django convention is.

Logins (see #2)
ID (PK)
username (here for convenience)
passwordSalt
passwordHash
relatedUserID (CustomUsers.ID)

CustomUsers (see #2 )
ID (PK)
firstName
lastName
username
creationDate

Profiles (see #4)
ID (PK)
relatedUserID (CustomUsers.ID)
bio
helpWanted
canHelp

BuddyRequests (see #10)
ID (PK)
requestSent (timestamp)
requestee (CustomUsers.ID)
requestor (CustomUsers.ID)

Not sure how we want to keep track of slowly changing dimensions yet, but the above basically ignores that issue for now (e.g. no way to keep track of changes in username over time or bio changes over time)

The above is also missing tracking for accepted BuddyRequests at the moment.

**Comment by alysivji** [comment]
What's the difference between `Logins` and `CustomUsers`?

**Comment by rifferreinert** [comment]
I think `Logins` contain just the information needed to authenticate the user while `CustomUsers` contains some information about the user him/herself. I'm not sure if we officially decided if this would be one to one or one to many.

**Comment by alysivji** [comment]
Is there a reason for splitting data across two classes? I would recommend starting off with a simple model and adding complexity as required. The [Django User Model](https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#django.contrib.auth.models.User) is a good place to start.

Having a `matching` app with a `Profile` model that is linked to `User` (1-to-1 or 1-to-many) and a many-to-many `BuddyRequest` table would work perfectly with this setup.

**Comment by ZaxR** [comment]
This is why I wanted to do it upfront: https://www.donedone.com/building-the-optimal-user-database-model-for-your-application/

**Comment by ZaxR** [comment]
@alysivji - the matching app / Profile and User models w/ BuddyRequests is what I had in mind.

**Comment by alysivji** [comment]
I think you're solving problems you don't have at the moment. It's hard to justify a need for additional complexity for a web app that has 1 account representing 1 user.

I'm gonna go ahead and close my PR. The work is there for the team to build off.

**Comment by ZaxR** [comment]
Thanks for the work and comments. After digging into it tonight it doesn't look like it's worth the effort. Splitting the two would basically require recreating the security features (e.g. password salt/hashing), which seems like a bad idea. The three biggest reasons to separate the tables out had been associating different user accounts, being able to have users without logins, and isolating passwords for security reasons. Looks like social login will help us with the first of those issues, and the other two really aren't that important.

**Comment by ZaxR** [comment]
Updated data model inplace above

**Comment by alysivji** [comment]
One of my favourite things about Django is that it usually makes the right decisions for you. =D

Customer User model aside =P
