### ISSUE TITLE
Write email copy for requests

### ISSUE THREAD

**Issue by ecxia** [chicagopython/buddy_mentorship#83]
Emails needed:
- Received a request
- Request accepted
- Received an offer
- Offer requested

Email copy should explain process.

**Comment by ZaxR** [comment]
For the e-mail titles:
```
New ChiPy {Mentor|Mentee} Request!
ChiPy {Mentor|Mentee} Request Accepted!
```

For the bodies, just remove the word "buddy" where it appears.
